In [1]:
import os, sys
import warnings

main_path = os.getcwd()

if not sys.warnoptions:
    warnings.simplefilter("ignore")

In [15]:
# Data manipulation
import numpy as np
import pandas as pd
import datetime

# Plotting
import matplotlib.pyplot as plt
import seaborn
import matplotlib.mlab as mlab

# Statistical manipulation
from scipy.stats import norm
from scipy.stats import kurtosis
from scipy.stats import skew
from scipy.stats import jarque_bera

# Tabulate data
from tabulate import tabulate

#df_vda = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180731.csv"))

In [3]:
# Load
df_cpa1 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180706.csv"))
df_cpa2 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180713.csv"))
df_cpa3 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180731.csv"))
df_cpa4 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180807.csv"))
df_cpa5 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180822.csv"))
df_cpa6 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180828.csv"))
df_cpa7 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180905.csv"))
df_cpa8 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180906.csv"))
df_cpa9 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20180921.csv"))
df_cpa10 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20181016.csv"))
df_cpa11 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20181022.csv"))
df_cpa12 = pd.read_csv(os.path.join(main_path, r"Bases\\VDA\\OFER_VDA_20181122.csv"))

In [4]:
#df_cpa = pd.concat([df_cpa1, df_cpa2, df_cpa3, df_cpa4, df_cpa5, df_cpa6, df_cpa7, df_cpa8, df_cpa9], ignore_index=True)
df_cpa = pd.concat([df_cpa1, df_cpa2, df_cpa3, df_cpa4, df_cpa5, df_cpa6, df_cpa7, df_cpa8, df_cpa9, df_cpa10, df_cpa11, df_cpa12], ignore_index=True)

In [5]:
SUZB3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='SUZB3                                             ']
SUZB3 = SUZB3.sort_values(by=['Hora_Prioridade'])

MGLU3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='MGLU3                                             ']
MGLU3 = MGLU3.sort_values(by=['Hora_Prioridade'])

FIBR3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='FIBR3                                             ']
FIBR3 = FIBR3.sort_values(by=['Hora_Prioridade'])

BTOW3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='BTOW3                                             ']
BTOW3 = BTOW3.sort_values(by=['Hora_Prioridade'])

VALE3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='VALE3                                             ']
VALE3 = VALE3.sort_values(by=['Hora_Prioridade'])

BRKM5 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='BRKM5                                             ']
BRKM5 = BRKM5.sort_values(by=['Hora_Prioridade'])

EMBR3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='EMBR3                                             ']
EMBR3 = EMBR3.sort_values(by=['Hora_Prioridade'])

PETR4 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='PETR4                                             ']
PETR4 = PETR4.sort_values(by=['Hora_Prioridade'])

CPFE3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='CPFE3                                             ']
CPFE3 = CPFE3.sort_values(by=['Hora_Prioridade'])

KLBN4 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='KLBN4                                             ']
KLBN4 = KLBN4.sort_values(by=['Hora_Prioridade'])

BRFS3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='BRFS3                                             ']
BRFS3 = BRFS3.sort_values(by=['Hora_Prioridade'])

KROT3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='KROT3                                             ']
KROT3 = KROT3.sort_values(by=['Hora_Prioridade'])

ELET6 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='ELET6                                             ']
ELET6 = ELET6.sort_values(by=['Hora_Prioridade'])

QUAL3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='QUAL3                                             ']
QUAL3 = QUAL3.sort_values(by=['Hora_Prioridade'])

UGPA3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='UGPA3                                             ']
UGPA3 = UGPA3.sort_values(by=['Hora_Prioridade'])

ECOR3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='ECOR3                                             ']
ECOR3 = ECOR3.sort_values(by=['Hora_Prioridade'])

ELET3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='ELET3                                             ']
ELET3 = ELET3.sort_values(by=['Hora_Prioridade'])

CCRO3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='CCRO3                                             ']
CCRO3 = CCRO3.sort_values(by=['Hora_Prioridade'])

SBSP3 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='SBSP3                                             ']
SBSP3 = SBSP3.sort_values(by=['Hora_Prioridade'])

GOLL4 = df_cpa.loc[df_cpa.Símbolo_do_Instrumento=='GOLL4                                             ']
GOLL4 = GOLL4.sort_values(by=['Hora_Prioridade'])
#GOLL4['return'] = GOLL4.Preço_Of_Compra.pct_change()
#is_inf = GOLL4['return'].iloc[:] == np.inf
#GOLL4['return'] = GOLL4['return'].loc[~is_inf, ]
#mean_GOLL4 = np.mean(GOLL4['return'])
#std_GOLL4 = np.std(GOLL4['return'])


In [6]:
# Transforma para segundos o horario de prioridade
def time_to_second(data):
    data['parts'] = data['Hora_Prioridade'].apply(lambda x: x.split(':'))
    data['seconds'] = data['parts'].apply(lambda x: round(int(x[0])*(60*60) + int(x[1])*60 + float(x[2])))

# calcula a media de preco da acao num intervalo de 5minutos    
def media_temp(data, gran = 300):
    init = data['seconds'].iloc[0]
    end = data['seconds'].iloc[-1]
    lista = []
    media = []
    for i in range(len(data)):
        if data['seconds'].iloc[i] - init <= gran:
            lista.append(data['Preço_Of_Compra'].iloc[i])
        else:
            media.append(np.sum(lista) / len(lista))
            lista = []
            init = data['seconds'].iloc[i]
    
    headers = ['mean']
    
    df = pd.DataFrame(data = media, columns = headers)
    df['return'] = df['mean'].pct_change()
        
    return df

In [7]:
# SUZB3
time_to_second(SUZB3)
SUZB3      = media_temp(SUZB3)
mean_SUZB3 = np.mean(SUZB3['return'])
std_SUZB3  = np.std(SUZB3['return'])

# MGLU3
time_to_second(MGLU3)
MGLU3      = media_temp(MGLU3)
mean_MGLU3 = np.mean(MGLU3['return'])
std_MGLU3  = np.std(MGLU3['return'])

# FIBR3
time_to_second(FIBR3)
FIBR3      = media_temp(FIBR3)
mean_FIBR3 = np.mean(FIBR3['return'])
std_FIBR3  = np.std(FIBR3['return'])

# BTOW3
time_to_second(BTOW3)
BTOW3      = media_temp(BTOW3)
mean_BTOW3 = np.mean(BTOW3['return'])
std_BTOW3  = np.std(BTOW3['return'])

# VALE3
time_to_second(VALE3)
VALE3      = media_temp(VALE3)
mean_VALE3 = np.mean(VALE3['return'])
std_VALE3  = np.std(VALE3['return'])

# BRKM5
time_to_second(BRKM5)
BRKM5      = media_temp(BRKM5)
mean_BRKM5 = np.mean(BRKM5['return'])
std_BRKM5  = np.std(BRKM5['return'])

# EMBR3
time_to_second(EMBR3)
EMBR3      = media_temp(EMBR3)
mean_EMBR3 = np.mean(EMBR3['return'])
std_EMBR3  = np.std(EMBR3['return'])

# PETR4
time_to_second(PETR4)
PETR4      = media_temp(PETR4)
mean_PETR4 = np.mean(PETR4['return'])
std_PETR4  = np.std(PETR4['return'])

# CPFE3
time_to_second(CPFE3)
CPFE3      = media_temp(CPFE3)
mean_CPFE3 = np.mean(CPFE3['return'])
std_CPFE3  = np.std(CPFE3['return'])

# KLBN4
time_to_second(KLBN4)
KLBN4      = media_temp(KLBN4)
mean_KLBN4 = np.mean(KLBN4['return'])
std_KLBN4  = np.std(KLBN4['return'])

# BRFS3
time_to_second(BRFS3)
BRFS3      = media_temp(BRFS3)
mean_BRFS3 = np.mean(BRFS3['return'])
std_BRFS3  = np.std(BRFS3['return'])

# KROT3
time_to_second(KROT3)
KROT3      = media_temp(KROT3)
mean_KROT3 = np.mean(KROT3['return'])
std_KROT3  = np.std(KROT3['return'])

# ELET6
time_to_second(ELET6)
ELET6      = media_temp(ELET6)
mean_ELET6 = np.mean(ELET6['return'])
std_ELET6  = np.std(ELET6['return'])

# QUAL3
time_to_second(QUAL3)
QUAL3      = media_temp(QUAL3)
mean_QUAL3 = np.mean(QUAL3['return'])
std_QUAL3  = np.std(QUAL3['return'])

# UGPA3
time_to_second(UGPA3)
UGPA3      = media_temp(UGPA3)
mean_UGPA3 = np.mean(UGPA3['return'])
std_UGPA3  = np.std(UGPA3['return'])

# ECOR3
time_to_second(ECOR3)
ECOR3      = media_temp(ECOR3)
mean_ECOR3 = np.mean(ECOR3['return'])
std_ECOR3  = np.std(ECOR3['return'])

# ELET3
time_to_second(ELET3)
ELET3      = media_temp(ELET3)
mean_ELET3 = np.mean(ELET3['return'])
std_ELET3  = np.std(ELET3['return'])

# CCRO3
time_to_second(CCRO3)
CCRO3      = media_temp(CCRO3)
mean_CCRO3 = np.mean(CCRO3['return'])
std_CCRO3  = np.std(CCRO3['return'])

# SBSP3
time_to_second(SBSP3)
SBSP3      = media_temp(SBSP3)
mean_SBSP3 = np.mean(SBSP3['return'])
std_SBSP3  = np.std(SBSP3['return'])

# GOLL4
time_to_second(GOLL4)
GOLL4      = media_temp(GOLL4)
mean_GOLL4 = np.mean(GOLL4['return'])
std_GOLL4  = np.std(GOLL4['return'])

In [8]:
best = [
SUZB3,
MGLU3,
FIBR3,
BTOW3,
VALE3,
BRKM5,
EMBR3,
PETR4,
CPFE3,
KLBN4]

worst = [
BRFS3,
KROT3,
ELET6,
QUAL3,
UGPA3,
ECOR3,
ELET3,
CCRO3,
SBSP3,
GOLL4]

In [ ]:
ELET6['return'].hist(bins = 100, normed = True, histtype = 'stepfilled', alpha = 1)
x = np.linspace(mean_ELET6 - 3*std_ELET6, mean_ELET6 + 3*std_ELET6,100)
plt.plot(x,mlab.normpdf(x, mean_ELET6,std_ELET6),"r")
plt.show()

In [ ]:
for i in best:
    i.hist(column = 'return', bins = 100, normed = True, histtype = 'stepfilled', alpha = 1, label = 'i')
    plt.ylabel('Frequency')

In [ ]:
for i in worst:
    i.hist(column = 'return', bins = 100, normed = True, histtype = 'stepfilled', alpha = 1, label = i)

In [9]:
VaR_90 = [
norm.ppf(1-0.9, mean_SUZB3, std_SUZB3),
norm.ppf(1-0.9, mean_MGLU3, std_MGLU3),
norm.ppf(1-0.9, mean_FIBR3, std_FIBR3),
norm.ppf(1-0.9, mean_BTOW3, std_BTOW3),
norm.ppf(1-0.9, mean_VALE3, std_VALE3),
norm.ppf(1-0.9, mean_BRKM5, std_BRKM5),
norm.ppf(1-0.9, mean_EMBR3, std_EMBR3),
norm.ppf(1-0.9, mean_PETR4, std_PETR4),
norm.ppf(1-0.9, mean_CPFE3, std_CPFE3),
norm.ppf(1-0.9, mean_KLBN4, std_KLBN4),
norm.ppf(1-0.9, mean_BRFS3, std_BRFS3),
norm.ppf(1-0.9, mean_KROT3, std_KROT3),
norm.ppf(1-0.9, mean_ELET6, std_ELET6),
norm.ppf(1-0.9, mean_QUAL3, std_QUAL3),
norm.ppf(1-0.9, mean_UGPA3, std_UGPA3),
norm.ppf(1-0.9, mean_ECOR3, std_ECOR3),
norm.ppf(1-0.9, mean_ELET3, std_ELET3),
norm.ppf(1-0.9, mean_CCRO3, std_CCRO3),
norm.ppf(1-0.9, mean_SBSP3, std_SBSP3),
norm.ppf(1-0.9, mean_GOLL4, std_GOLL4)]

VaR_95 = [
norm.ppf(1-0.95, mean_SUZB3, std_SUZB3),
norm.ppf(1-0.95, mean_MGLU3, std_MGLU3),
norm.ppf(1-0.95, mean_FIBR3, std_FIBR3),
norm.ppf(1-0.95, mean_BTOW3, std_BTOW3),
norm.ppf(1-0.95, mean_VALE3, std_VALE3),
norm.ppf(1-0.95, mean_BRKM5, std_BRKM5),
norm.ppf(1-0.95, mean_EMBR3, std_EMBR3),
norm.ppf(1-0.95, mean_PETR4, std_PETR4),
norm.ppf(1-0.95, mean_CPFE3, std_CPFE3),
norm.ppf(1-0.95, mean_KLBN4, std_KLBN4),
norm.ppf(1-0.95, mean_BRFS3, std_BRFS3),
norm.ppf(1-0.95, mean_KROT3, std_KROT3),
norm.ppf(1-0.95, mean_ELET6, std_ELET6),
norm.ppf(1-0.95, mean_QUAL3, std_QUAL3),
norm.ppf(1-0.95, mean_UGPA3, std_UGPA3),
norm.ppf(1-0.95, mean_ECOR3, std_ECOR3),
norm.ppf(1-0.95, mean_ELET3, std_ELET3),
norm.ppf(1-0.95, mean_CCRO3, std_CCRO3),
norm.ppf(1-0.95, mean_SBSP3, std_SBSP3),
norm.ppf(1-0.95, mean_GOLL4, std_GOLL4)
]

print(tabulate([['90%', VaR_90[0], VaR_90[1], VaR_90[2], VaR_90[3], VaR_90[4], VaR_90[5], VaR_90[6], VaR_90[7], VaR_90[8], VaR_90[9]],
                ['95%', VaR_95[0], VaR_95[1], VaR_95[2], VaR_95[3], VaR_95[4], VaR_95[5], VaR_95[6], VaR_95[7], VaR_95[8], VaR_95[9]]], 
               headers = ['CL_best', 'SUZB3', 'MGLU3','FIBR3', 'BTOW3', 'VALE3', 'BRKM5', 'EMBR3','PETR4', 'CPFE3', 'KLBN4']))



print(tabulate([['90%', VaR_90[10], VaR_90[11], VaR_90[12], VaR_90[13], VaR_90[14], VaR_90[15], VaR_90[16], VaR_90[17], VaR_90[18], VaR_90[19]],
                ['95%', VaR_95[10], VaR_95[11], VaR_95[12], VaR_95[13], VaR_95[14], VaR_95[15], VaR_95[16], VaR_95[17], VaR_95[18], VaR_95[19]]], 
               headers = ['CL_worst', 'BRFS3', 'KROT3','ELET6', 'QUAL3', 'UGPA3', 'ECOR3', 'ELET3','CCRO3', 'SBSP3', 'GOLL4']))

CL_best        SUZB3       MGLU3      FIBR3      BTOW3      VALE3      BRKM5      EMBR3      PETR4       CPFE3      KLBN4
---------  ---------  ----------  ---------  ---------  ---------  ---------  ---------  ---------  ----------  ---------
90%        -0.151425  -0.0690301  -0.123946  -0.209928  -0.156145  -0.144838  -0.223556  -0.319973  -0.0915179  -0.514032
95%        -0.196239  -0.0888636  -0.159847  -0.271729  -0.202148  -0.184298  -0.289903  -0.416498  -0.117951   -0.677328
CL_worst        BRFS3      KROT3      ELET6      QUAL3      UGPA3       ECOR3      ELET3     CCRO3      SBSP3      GOLL4
----------  ---------  ---------  ---------  ---------  ---------  ----------  ---------  --------  ---------  ---------
90%         -0.217986  -0.158913  -0.386875  -0.203928  -0.1965    -0.0925091  -0.255084  -0.12462  -0.230118  -0.113224
95%         -0.283484  -0.205437  -0.503718  -0.265098  -0.255257  -0.119327   -0.329987  -0.16001  -0.298184  -0.145963


In [ ]:
SUZB3.head(5)

In [ ]:
for i in best:
    i.sort_values('return', inplace = True, ascending = True)

In [12]:
kurto_index = []
for i in best:
    kurto_index.append(kurtosis(i['return'][1:]))
for i in worst:
    kurto_index.append(kurtosis(i['return'][1:]))

skew_index = []
for i in best:
    skew_index.append(skew(i['return'][1:]))
for i in worst:
    skew_index.append(skew(i['return'][1:]))
    
print(tabulate([['Kurtosis index', kurto_index[0], kurto_index[1], kurto_index[2], kurto_index[3], kurto_index[4], kurto_index[5], kurto_index[6], kurto_index[7], kurto_index[8], kurto_index[9]],
                ['skew index', skew_index[0], skew_index[1], skew_index[2], skew_index[3], skew_index[4], skew_index[5], skew_index[6], skew_index[7], skew_index[8], skew_index[9]]], 
               headers = ['Index best', 'SUZB3', 'MGLU3','FIBR3', 'BTOW3', 'VALE3', 'BRKM5', 'EMBR3','PETR4', 'CPFE3', 'KLBN4']))


print(tabulate([['Kurtosis index ', kurto_index[10], kurto_index[11], kurto_index[12], kurto_index[13], kurto_index[14], kurto_index[15], kurto_index[16], kurto_index[17], kurto_index[18], kurto_index[19]],
                ['skew index', skew_index[10], skew_index[11], skew_index[12], skew_index[13], skew_index[14], skew_index[15], skew_index[16], skew_index[17], skew_index[18], skew_index[19]]], 
               headers = ['Index worst', 'BRFS3', 'KROT3','ELET6', 'QUAL3', 'UGPA3', 'ECOR3', 'ELET3','CCRO3', 'SBSP3', 'GOLL4']))

Index best         SUZB3      MGLU3     FIBR3     BTOW3     VALE3     BRKM5     EMBR3     PETR4     CPFE3     KLBN4
--------------  --------  ---------  --------  --------  --------  --------  --------  --------  --------  --------
Kurtosis index  24.448    13.3457    14.914    48.6408   56.317    16.7975   53.9705   73.2689   37.7306   20.7119
skew index       3.75927  -0.113345   1.33439   6.10064   5.91734   1.52529   6.23708   7.70924   4.91902   3.71494
Index worst        BRFS3     KROT3     ELET6     QUAL3     UGPA3      ECOR3     ELET3     CCRO3    SBSP3    GOLL4
--------------  --------  --------  --------  --------  --------  ---------  --------  --------  -------  -------
Kurtosis index  27.1623   35.0475   67.277    50.8575   17.9911   11.4466    25.9021   21.8741   48.8381  6.53304
skew index       4.05862   4.56315   7.58619   5.76779   2.76502   0.419453   3.11303   2.36723   6.1683  1.51768


In [14]:
myList = list(np.around(np.array(skew_index),2))
myList

[3.76,
 -0.11,
 1.33,
 6.1,
 5.92,
 1.53,
 6.24,
 7.71,
 4.92,
 3.71,
 4.06,
 4.56,
 7.59,
 5.77,
 2.77,
 0.42,
 3.11,
 2.37,
 6.17,
 1.52]

In [16]:
JB_index = []
for i in best:
    JB_index.append(jarque_bera(i['return'][1:]))
for i in worst:
    JB_index.append(jarque_bera(i['return'][1:]))

jar = list(np.around(np.array(JB_index),2))
jar

[array([2862.27,    0.  ]),
 array([772.02,   0.  ]),
 array([985.15,   0.  ]),
 array([10897.46,     0.  ]),
 array([14488.51,     0.  ]),
 array([1250.85,    0.  ]),
 array([13424.35,     0.  ]),
 array([25928.02,     0.  ]),
 array([6461.64,    0.  ]),
 array([1997.27,    0.  ]),
 array([3549.59,    0.  ]),
 array([5792.97,    0.  ]),
 array([20016.52,     0.  ]),
 array([11784.74,     0.  ]),
 array([1505.61,    0.  ]),
 array([570.83,   0.  ]),
 array([3134.44,    0.  ]),
 array([2170.53,    0.  ]),
 array([10783.76,     0.  ]),
 array([235.69,   0.  ])]

In [ ]:
MGLU3

# Expected Shortfall

In [10]:
# SUZB3
SUZB3.sort_values('return', inplace = True, ascending = True)

# MGLU3
MGLU3.sort_values('return', inplace = True, ascending = True)

# FIBR3
FIBR3.sort_values('return', inplace = True, ascending = True)

# BTOW3
BTOW3.sort_values('return', inplace = True, ascending = True)

# VALE3
VALE3.sort_values('return', inplace = True, ascending = True)

# BRKM5
BRKM5.sort_values('return', inplace = True, ascending = True)

# EMBR3
EMBR3.sort_values('return', inplace = True, ascending = True)

# PETR4
PETR4.sort_values('return', inplace = True, ascending = True)

# CPFE3
CPFE3.sort_values('return', inplace = True, ascending = True)

# KLBN4
KLBN4.sort_values('return', inplace = True, ascending = True)

# BRFS3
BRFS3.sort_values('return', inplace = True, ascending = True)

# KROT3
KROT3.sort_values('return', inplace = True, ascending = True)

# ELET6
ELET6.sort_values('return', inplace = True, ascending = True)

# QUAL3
QUAL3.sort_values('return', inplace = True, ascending = True)

# UGPA3
UGPA3.sort_values('return', inplace = True, ascending = True)

# ECOR3
ECOR3.sort_values('return', inplace = True, ascending = True)

# ELET3
ELET3.sort_values('return', inplace = True, ascending = True)

# CCRO3
CCRO3.sort_values('return', inplace = True, ascending = True)

# SBSP3
SBSP3.sort_values('return', inplace = True, ascending = True)

# GOLL4
GOLL4.sort_values('return', inplace = True, ascending = True)

In [11]:
ES_90 = [
SUZB3['return'].quantile(0.1),
MGLU3['return'].quantile(0.1),
FIBR3['return'].quantile(0.1),
BTOW3['return'].quantile(0.1),
VALE3['return'].quantile(0.1),
BRKM5['return'].quantile(0.1),
EMBR3['return'].quantile(0.1),
PETR4['return'].quantile(0.1),
CPFE3['return'].quantile(0.1),
KLBN4['return'].quantile(0.1),
BRFS3['return'].quantile(0.1),
KROT3['return'].quantile(0.1),
ELET6['return'].quantile(0.1),
QUAL3['return'].quantile(0.1),
UGPA3['return'].quantile(0.1),
ECOR3['return'].quantile(0.1),
ELET3['return'].quantile(0.1),
CCRO3['return'].quantile(0.1),
SBSP3['return'].quantile(0.1),
GOLL4['return'].quantile(0.1)    
]

ES_95 = [
SUZB3['return'].quantile(0.05),
MGLU3['return'].quantile(0.05),
FIBR3['return'].quantile(0.05),
BTOW3['return'].quantile(0.05),
VALE3['return'].quantile(0.05),
BRKM5['return'].quantile(0.05),
EMBR3['return'].quantile(0.05),
PETR4['return'].quantile(0.05),
CPFE3['return'].quantile(0.05),
KLBN4['return'].quantile(0.05),
BRFS3['return'].quantile(0.05),
KROT3['return'].quantile(0.05),
ELET6['return'].quantile(0.05),
QUAL3['return'].quantile(0.05),
UGPA3['return'].quantile(0.05),
ECOR3['return'].quantile(0.05),
ELET3['return'].quantile(0.05),
CCRO3['return'].quantile(0.05),
SBSP3['return'].quantile(0.05),
GOLL4['return'].quantile(0.05)    
]

print(tabulate([['90%', ES_90[0], ES_90[1], ES_90[2], ES_90[3], ES_90[4], ES_90[5], ES_90[6], ES_90[7], ES_90[8], ES_90[9]],
                ['95%', ES_95[0], ES_95[1], ES_95[2], ES_95[3], ES_95[4], ES_95[5], ES_95[6], ES_95[7], ES_95[8], ES_95[9]]], 
               headers = ['CL_best', 'SUZB3', 'MGLU3','FIBR3', 'BTOW3', 'VALE3', 'BRKM5', 'EMBR3','PETR4', 'CPFE3', 'KLBN4']))



print(tabulate([['90%', ES_90[10], ES_90[11], ES_90[12], ES_90[13], ES_90[14], ES_90[15], ES_90[16], ES_90[17], ES_90[18], ES_90[19]],
                ['95%', ES_95[10], ES_95[11], ES_95[12], ES_95[13], ES_95[14], ES_95[15], ES_95[16], ES_95[17], ES_95[18], ES_95[19]]], 
               headers = ['CL_worst', 'BRFS3', 'KROT3','ELET6', 'QUAL3', 'UGPA3', 'ECOR3', 'ELET3','CCRO3', 'SBSP3', 'GOLL4']))

CL_best         SUZB3       MGLU3       FIBR3       BTOW3       VALE3       BRKM5       EMBR3       PETR4       CPFE3      KLBN4
---------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ---------
90%        -0.0231671  -0.0391191  -0.0133641  -0.0377702  -0.0224448  -0.0291133  -0.031625   -0.0532593  -0.0276849  -0.266806
95%        -0.0975994  -0.0528064  -0.0782284  -0.0681375  -0.0524826  -0.144729   -0.0703762  -0.100113   -0.0796665  -0.394703
CL_worst         BRFS3       KROT3       ELET6       QUAL3       UGPA3       ECOR3       ELET3       CCRO3       SBSP3       GOLL4
----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------
90%         -0.0378225  -0.0504834  -0.0604264  -0.0458245  -0.0309741  -0.0203909  -0.0583159  -0.0304408  -0.0264682  -0.0801531
95%         -0.0730396  -0.0988007  -0.0920895  -0.0750622  -0.0897961  -0.0666395  -0.1006